MOLLI:=datasets/Mollicutes/
QUASTMOLLI:= $(QUAST) --gene-finding --gene-thresholds 0,100,300,500,1000,1500,3000

result_statistics/all_myco/MSCD_QUAST: 	$(MOLLI)/MSCd/AKE_ABySS_34-scaffolds.fasta $(MOLLI)/MSCd/AKE_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MSCd/AKE_step2_out.unpadded.fasta \
result_assemblies/MSCd_AB_CLC_mix.fasta result_assemblies/MSCd_AB_MIRA_mix.fasta result_assemblies/MSCd_CLC_MIRA_mix.fasta \
datasets/GAA/Mycoplasme/MSCd/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MSCd/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MSCd/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MSCd/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MSCd/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MSCd/GAA_MIRA-CLC.fa \
datasets/GAM-NGS/Mollicutes/MSCd/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mollicutes/MSCd/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mollicutes/MSCd/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mollicutes/MSCd/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mollicutes/MSCd/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mollicutes/MSCd/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
	
result_statistics/all_myco/MSCC_QUAST: 	$(MOLLI)/MSCc/AIZ_ABySS_27-scaffolds.fasta $(MOLLI)/MSCc/AIZ_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MSCc/AIZ_step2_out.unpadded.fasta \
result_assemblies/MSCc_AB_CLC_mix.fasta result_assemblies/MSCc_AB_MIRA_mix.fasta result_assemblies/MSCc_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MSCc/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MSCc/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MSCc/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MSCc/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MSCc/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MSCc/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mollicutes/MSCc/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mollicutes/MSCc/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mollicutes/MSCc/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mollicutes/MSCc/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mollicutes/MSCc/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mollicutes/MSCc/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MSCB_QUAST: 	$(MOLLI)/MSCb/AIY_ABySS_29-scaffolds.fasta $(MOLLI)/MSCb/AIY_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MSCb/AIY_step2_out.unpadded.fasta \
result_assemblies/MSCb_AB_CLC_mix.fasta result_assemblies/MSCb_AB_MIRA_mix.fasta result_assemblies/MSCb_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MSCb/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MSCb/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MSCb/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MSCb/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MSCb/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MSCb/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mollicutes/MSCb/GAM_CLC-abyss.fasta datasets/GAM-NGS/Mollicutes/MSCb/GAM_CLC-mira.fasta datasets/GAM-NGS/Mollicutes/MSCb/GAM_abyss-CLC.fasta datasets/GAM-NGS/Mollicutes/MSCb/GAM_mira-abyss.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MOVI_QUAST: 	$(MOLLI)/MOVI/AIP_ABySS_32-scaffolds.fasta $(MOLLI)/MOVI/AIP_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MOVI/AIP_step2_out.unpadded.fasta \
result_assemblies/MOVI_AB_CLC_mix.fasta result_assemblies/MOVI_AB_MIRA_mix.fasta result_assemblies/MOVI_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MOVI/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MOVI/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MOVI/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MOVI/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MOVI/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MOVI/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mollicutes/MOVI/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mollicutes/MOVI/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mollicutes/MOVI/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mollicutes/MOVI/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mollicutes/MOVI/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mollicutes/MOVI/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MMC_QUAST: 	$(MOLLI)/MMC/AIW_ABySS_30-scaffolds.fasta $(MOLLI)/MMC/AIW_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MMC/AIW_step2_out.unpadded.fasta \
	result_assemblies/MMC_AB_CLC_mix.fasta result_assemblies/MMC_AB_MIRA_mix.fasta result_assemblies/MMC_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MMC/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MMC/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MMC/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MMC/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MMC/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MMC/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mollicutes/MMC/GAM_CLC-mira.fasta datasets/GAM-NGS/Mollicutes/MMC/GAM_abyss-CLC.fasta datasets/GAM-NGS/Mollicutes/MMC/GAM_mira-abyss.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MCCP_QUAST: 	$(MOLLI)/MMC/AIW_ABySS_30-scaffolds.fasta $(MOLLI)/MMC/AIW_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MMC/AIW_step2_out.unpadded.fasta \
	$(MOLLI)/MCCP/AIX_ABySS_35-scaffolds.fasta $(MOLLI)/MCCP/AIX_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MCCP/AIX_step2_out.unpadded.fasta \
result_assemblies/MCCP_AB_CLC_mix.fasta result_assemblies/MCCP_AB_MIRA_mix.fasta result_assemblies/MCCP_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MCCP/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MCCP/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MCCP/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MCCP/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MCCP/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MCCP/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mollicutes/MCCP/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mollicutes/MCCP/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mollicutes/MCCP/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mollicutes/MCCP/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mollicutes/MCCP/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mollicutes/MCCP/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MBVG_QUAST: 	$(MOLLI)/MBVG/AIN_ABySS_35-scaffolds.fasta $(MOLLI)/MBVG/AIN_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MBVG/AIN_step2_out.unpadded.fasta \
	result_assemblies/MBVG_AB_CLC_mix.fasta result_assemblies/MBVG_AB_MIRA_mix.fasta result_assemblies/MBVG_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MBVG/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MBVG/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MBVG/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MBVG/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MBVG/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MBVG/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mollicutes/MBVG/GAM_CLC-mira.fasta datasets/GAM-NGS/Mollicutes/MBVG/GAM_abyss-CLC.fasta datasets/GAM-NGS/Mollicutes/MBVG/GAM_mira-abyss.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MBOVb_QUAST: $(MOLLI)/MBOVb/AIQ_ABySS_34-scaffolds.fasta $(MOLLI)/MBOVb/AIQ_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MBOVb/AIQ_step2_out.unpadded.fasta \
	result_assemblies/MBOVb_AB_CLC_mix.fasta result_assemblies/MBOVb_AB_MIRA_mix.fasta result_assemblies/MBOVb_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MBOVb/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MBOVb/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MBOVb/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MBOVb/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MBOVb/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MBOVb/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mollicutes/MBOVb/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mollicutes/MBOVb/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mollicutes/MBOVb/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mollicutes/MBOVb/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mollicutes/MBOVb/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mollicutes/MBOVb/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MAUR_QUAST: 	$(MOLLI)/MAUR/AIM_ABySS_27-scaffolds.fasta $(MOLLI)/MAUR/AIM_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MAUR/AIM_step2_out.unpadded.fasta \
	result_assemblies/MAUR_AB_CLC_mix.fasta result_assemblies/MAUR_AB_MIRA_mix.fasta result_assemblies/MAUR_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MAUR/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MAUR/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MAUR/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MAUR/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MAUR/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MAUR/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mollicutes/MAUR/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mollicutes/MAUR/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mollicutes/MAUR/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mollicutes/MAUR/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mollicutes/MAUR/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mollicutes/MAUR/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MSCE_QUAST: 	$(MOLLI)/MSCe/AKC_ABySS_35-scaffolds.fasta $(MOLLI)/MSCe/AKC_CLC_contigsCLCTrimmed_0.fasta $(MOLLI)/MSCe/AKC_step2_out.unpadded.fasta \
result_assemblies/MSCe_AB_CLC_mix.fasta result_assemblies/MSCe_AB_MIRA_mix.fasta result_assemblies/MSCe_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MSCe/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MSCe/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MSCe/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MSCe/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MSCe/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MSCe/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mollicutes/MSCe/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mollicutes/MSCe/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mollicutes/MSCe/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mollicutes/MSCe/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mollicutes/MSCe/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mollicutes/MSCe/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^


ALLMYCOQUASTS:result_statistics/all_myco/MSCD_QUAST result_statistics/all_myco/MSCC_QUAST result_statistics/all_myco/MSCB_QUAST result_statistics/all_myco/MOVI_QUAST result_statistics/all_myco/MMC_QUAST result_statistics/all_myco/MCCP_QUAST result_statistics/all_myco/MBVG_QUAST result_statistics/all_myco/MBOVb_QUAST result_statistics/all_myco/MAUR_QUAST result_statistics/all_myco/MSCE_QUAST