MOLLI:=datasets/Mycoplasmas/
QUASTMOLLI:= $(QUAST) --gene-finding --gene-thresholds 0,100,300,500,1000,1500,3000

result_statistics/all_myco/MSCD_QUAST: 	$(MOLLI)/MSCd/MSCd_ABySS_34.fasta $(MOLLI)/MSCd/MSCd_CLC.fasta $(MOLLI)/MSCd/MSCd_MIRA.fasta \
result_assemblies/MSCd_AB_CLC_mix.fasta result_assemblies/MSCd_AB_MIRA_mix.fasta result_assemblies/MSCd_CLC_MIRA_mix.fasta \
datasets/GAA/Mycoplasme/MSCd/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MSCd/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MSCd/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MSCd/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MSCd/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MSCd/GAA_MIRA-CLC.fa \
datasets/GAM-NGS/Mycoplasmas/MSCd/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
	
result_statistics/all_myco/MSCc_QUAST: 	$(MOLLI)/MSCc/MSCc_ABySS_27 $(MOLLI)/MSCc/MSCc_CLC.fasta $(MOLLI)/MSCc/MSCc_MIRA.fasta \
result_assemblies/MSCc_AB_CLC_mix.fasta result_assemblies/MSCc_AB_MIRA_mix.fasta result_assemblies/MSCc_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MSCc/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MSCc/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MSCc/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MSCc/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MSCc/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MSCc/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mycoplasmas/MSCc/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MSCb_QUAST: 	$(MOLLI)/MSCb/MSCb_ABySS_29.fasta $(MOLLI)/MSCb/MSCb_CLC.fasta $(MOLLI)/MSCb/MSCb_MIRA.fasta \
result_assemblies/MSCb_AB_CLC_mix.fasta result_assemblies/MSCb_AB_MIRA_mix.fasta result_assemblies/MSCb_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MSCb/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MSCb/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MSCb/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MSCb/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MSCb/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MSCb/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mycoplasmas/MSCb/GAM_CLC-abyss.fasta datasets/GAM-NGS/Mycoplasmas/MSCb/GAM_CLC-mira.fasta datasets/GAM-NGS/Mycoplasmas/MSCb/GAM_abyss-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MSCb/GAM_mira-abyss.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MOVI_QUAST: 	$(MOLLI)/MOVI/MOVI_ABySS_32.fasta $(MOLLI)/MOVI/MOVI_CLC.fasta $(MOLLI)/MOVI/MOVI_MIRA.fasta \
result_assemblies/MOVI_AB_CLC_mix.fasta result_assemblies/MOVI_AB_MIRA_mix.fasta result_assemblies/MOVI_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MOVI/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MOVI/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MOVI/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MOVI/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MOVI/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MOVI/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mycoplasmas/MOVI/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MMC_QUAST: 	$(MOLLI)/MMC/MMC_ABySS_30.fasta $(MOLLI)/MMC/MMC_CLC.fasta $(MOLLI)/MMC/MMC_MIRA.fasta \
	result_assemblies/MMC_AB_CLC_mix.fasta result_assemblies/MMC_AB_MIRA_mix.fasta result_assemblies/MMC_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MMC/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MMC/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MMC/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MMC/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MMC/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MMC/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mycoplasmas/MMC/GAM_CLC-mira.fasta datasets/GAM-NGS/Mycoplasmas/MMC/GAM_abyss-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MMC/GAM_mira-abyss.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MCCP_QUAST: 	$(MOLLI)/MCCP/MCCP_ABySS_35.fasta $(MOLLI)/MCCP/MCCP_CLC.fasta $(MOLLI)/MCCP/MCCP_MIRA.fasta \
result_assemblies/MCCP_AB_CLC_mix.fasta result_assemblies/MCCP_AB_MIRA_mix.fasta result_assemblies/MCCP_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MCCP/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MCCP/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MCCP/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MCCP/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MCCP/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MCCP/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mycoplasmas/MCCP/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MBVG_QUAST: 	$(MOLLI)/MBVG/MBVG_ABySS_35.fasta $(MOLLI)/MBVG/MBVG_CLC.fasta $(MOLLI)/MBVG/MBVG_MIRA.fasta \
	result_assemblies/MBVG_AB_CLC_mix.fasta result_assemblies/MBVG_AB_MIRA_mix.fasta result_assemblies/MBVG_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MBVG/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MBVG/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MBVG/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MBVG/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MBVG/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MBVG/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mycoplasmas/MBVG/GAM_CLC-mira.fasta datasets/GAM-NGS/Mycoplasmas/MBVG/GAM_abyss-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MBVG/GAM_mira-abyss.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MBOVb_QUAST: $(MOLLI)/MBOVb/MBOVb_ABySS_34.fasta $(MOLLI)/MBOVb/MBOVb_CLC.fasta $(MOLLI)/MBOVb/MBOVb_MIRA.fasta \
	result_assemblies/MBOVb_AB_CLC_mix.fasta result_assemblies/MBOVb_AB_MIRA_mix.fasta result_assemblies/MBOVb_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MBOVb/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MBOVb/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MBOVb/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MBOVb/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MBOVb/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MBOVb/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mycoplasmas/MBOVb/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MAUR_QUAST: 	$(MOLLI)/MAUR/MAUR_ABySS_27.fasta $(MOLLI)/MAUR/MAUR_CLC.fasta $(MOLLI)/MAUR/MAUR_MIRA.fasta \
	result_assemblies/MAUR_AB_CLC_mix.fasta result_assemblies/MAUR_AB_MIRA_mix.fasta result_assemblies/MAUR_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MAUR/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MAUR/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MAUR/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MAUR/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MAUR/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MAUR/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mycoplasmas/MAUR/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MSCE_QUAST: 	$(MOLLI)/MSCe/MSCe_ABySS_35.fasta $(MOLLI)/MSCe/MSCe_CLC.fasta $(MOLLI)/MSCe/MSCe_MIRA.fasta \
result_assemblies/MSCe_AB_CLC_mix.fasta result_assemblies/MSCe_AB_MIRA_mix.fasta result_assemblies/MSCe_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasme/MSCe/GAA_AB-CLC.fa datasets/GAA/Mycoplasme/MSCe/GAA_AB-MIRA.fa datasets/GAA/Mycoplasme/MSCe/GAA_CLC-AB.fa datasets/GAA/Mycoplasme/MSCe/GAA_CLC-MIRA.fa datasets/GAA/Mycoplasme/MSCe/GAA_MIRA-AB.fa datasets/GAA/Mycoplasme/MSCe/GAA_MIRA-CLC.fa datasets/GAM-NGS/Mycoplasmas/MSCe/GAM_ABySS-CLC.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/GAM_ABySS-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/GAM_CLC-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/GAM_CLC-MIRA.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/GAM_MIRA-ABySS.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/GAM_MIRA-CLC.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^


ALLMYCOQUASTS:result_statistics/all_myco/MSCD_QUAST result_statistics/all_myco/MSCc_QUAST result_statistics/all_myco/MSCb_QUAST result_statistics/all_myco/MOVI_QUAST result_statistics/all_myco/MMC_QUAST result_statistics/all_myco/MCCP_QUAST result_statistics/all_myco/MBVG_QUAST result_statistics/all_myco/MBOVb_QUAST result_statistics/all_myco/MAUR_QUAST result_statistics/all_myco/MSCE_QUAST