MOLLI:=datasets/Mycoplasmas/
QUASTMOLLI:= $(QUAST) --gene-finding --gene-thresholds 0,100,300,500,1000,1500,3000

result_statistics/all_myco/MSCD_QUAST: 	$(MOLLI)/MSCd/MSCd_ABySS_34.fasta $(MOLLI)/MSCd/MSCd_CLC.fasta $(MOLLI)/MSCd/MSCd_MIRA.fasta \
result_assemblies/MSCd_AB_CLC_mix.fasta result_assemblies/MSCd_AB_MIRA_mix.fasta result_assemblies/MSCd_CLC_MIRA_mix.fasta \
datasets/GAA/Mycoplasmas/MSCd/MSCd_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MSCd/MSCd_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MSCd/MSCd_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MSCd/MSCd_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MSCd/MSCd_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MSCd/MSCd_MIRA-CLC_gaa.fasta \
datasets/GAM-NGS/Mycoplasmas/MSCd/MSCd_ABySS-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/MSCd_ABySS-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/MSCd_CLC-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/MSCd_CLC-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/MSCd_MIRA-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCd/MSCd_MIRA-CLC_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
	
result_statistics/all_myco/MSCc_QUAST: 	$(MOLLI)/MSCc/MSCc_ABySS_27.fasta $(MOLLI)/MSCc/MSCc_CLC.fasta $(MOLLI)/MSCc/MSCc_MIRA.fasta \
result_assemblies/MSCc_AB_CLC_mix.fasta result_assemblies/MSCc_AB_MIRA_mix.fasta result_assemblies/MSCc_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasmas/MSCc/MSCc_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MSCc/MSCc_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MSCc/MSCc_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MSCc/MSCc_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MSCc/MSCc_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MSCc/MSCc_MIRA-CLC_gaa.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/MSCc_ABySS-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/MSCc_ABySS-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/MSCc_CLC-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/MSCc_CLC-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/MSCc_MIRA-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCc/MSCc_MIRA-CLC_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MSCb_QUAST: 	$(MOLLI)/MSCb/MSCb_ABySS_29.fasta $(MOLLI)/MSCb/MSCb_CLC.fasta $(MOLLI)/MSCb/MSCb_MIRA.fasta \
result_assemblies/MSCb_AB_CLC_mix.fasta result_assemblies/MSCb_AB_MIRA_mix.fasta result_assemblies/MSCb_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasmas/MSCb/MSCb_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MSCb/MSCb_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MSCb/MSCb_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MSCb/MSCb_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MSCb/MSCb_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MSCb/MSCb_MIRA-CLC_gaa.fasta datasets/GAM-NGS/Mycoplasmas/MSCb/MSCb_CLC-abyss_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCb/MSCb_CLC-mira_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCb/MSCb_abyss-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCb/MSCb_mira-abyss_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MOVI_QUAST: 	$(MOLLI)/MOVI/MOVI_ABySS_32.fasta $(MOLLI)/MOVI/MOVI_CLC.fasta $(MOLLI)/MOVI/MOVI_MIRA.fasta \
result_assemblies/MOVI_AB_CLC_mix.fasta result_assemblies/MOVI_AB_MIRA_mix.fasta result_assemblies/MOVI_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasmas/MOVI/MOVI_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MOVI/MOVI_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MOVI/MOVI_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MOVI/MOVI_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MOVI/MOVI_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MOVI/MOVI_MIRA-CLC_gaa.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/MOVI_ABySS-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/MOVI_ABySS-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/MOVI_CLC-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/MOVI_CLC-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/MOVI_MIRA-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MOVI/MOVI_MIRA-CLC_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MMC_QUAST: 	$(MOLLI)/MMC/MMC_ABySS_30.fasta $(MOLLI)/MMC/MMC_CLC.fasta $(MOLLI)/MMC/MMC_MIRA.fasta \
	result_assemblies/MMC_AB_CLC_mix.fasta result_assemblies/MMC_AB_MIRA_mix.fasta result_assemblies/MMC_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasmas/MMC/MMC_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MMC/MMC_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MMC/MMC_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MMC/MMC_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MMC/MMC_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MMC/MMC_MIRA-CLC_gaa.fasta datasets/GAM-NGS/Mycoplasmas/MMC/MMC_CLC-mira_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MMC/MMC_abyss-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MMC/MMC_mira-abyss_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MCCP_QUAST: 	$(MOLLI)/MCCP/MCCP_ABySS_35.fasta $(MOLLI)/MCCP/MCCP_CLC.fasta $(MOLLI)/MCCP/MCCP_MIRA.fasta \
result_assemblies/MCCP_AB_CLC_mix.fasta result_assemblies/MCCP_AB_MIRA_mix.fasta result_assemblies/MCCP_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasmas/MCCP/MCCP_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MCCP/MCCP_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MCCP/MCCP_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MCCP/MCCP_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MCCP/MCCP_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MCCP/MCCP_MIRA-CLC_gaa.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/MCCP_ABySS-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/MCCP_ABySS-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/MCCP_CLC-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/MCCP_CLC-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/MCCP_MIRA-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MCCP/MCCP_MIRA-CLC_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MBVG_QUAST: 	$(MOLLI)/MBVG/MBVG_ABySS_35.fasta $(MOLLI)/MBVG/MBVG_CLC.fasta $(MOLLI)/MBVG/MBVG_MIRA.fasta \
	result_assemblies/MBVG_AB_CLC_mix.fasta result_assemblies/MBVG_AB_MIRA_mix.fasta result_assemblies/MBVG_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasmas/MBVG/MBVG_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MBVG/MBVG_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MBVG/MBVG_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MBVG/MBVG_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MBVG/MBVG_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MBVG/MBVG_MIRA-CLC_gaa.fasta datasets/GAM-NGS/Mycoplasmas/MBVG/MBVG_CLC-mira_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MBVG/MBVG_abyss-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MBVG/MBVG_mira-abyss_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MBOVb_QUAST: $(MOLLI)/MBOVb/MBOVb_ABySS_34.fasta $(MOLLI)/MBOVb/MBOVb_CLC.fasta $(MOLLI)/MBOVb/MBOVb_MIRA.fasta \
	result_assemblies/MBOVb_AB_CLC_mix.fasta result_assemblies/MBOVb_AB_MIRA_mix.fasta result_assemblies/MBOVb_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasmas/MBOVb/MBOVb_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MBOVb/MBOVb_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MBOVb/MBOVb_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MBOVb/MBOVb_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MBOVb/MBOVb_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MBOVb/MBOVb_MIRA-CLC_gaa.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/MBOVb_ABySS-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/MBOVb_ABySS-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/MBOVb_CLC-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/MBOVb_CLC-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/MBOVb_MIRA-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MBOVb/MBOVb_MIRA-CLC_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MAUR_QUAST: 	$(MOLLI)/MAUR/MAUR_ABySS_27.fasta $(MOLLI)/MAUR/MAUR_CLC.fasta $(MOLLI)/MAUR/MAUR_MIRA.fasta \
	result_assemblies/MAUR_AB_CLC_mix.fasta result_assemblies/MAUR_AB_MIRA_mix.fasta result_assemblies/MAUR_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasmas/MAUR/MAUR_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MAUR/MAUR_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MAUR/MAUR_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MAUR/MAUR_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MAUR/MAUR_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MAUR/MAUR_MIRA-CLC_gaa.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/MAUR_ABySS-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/MAUR_ABySS-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/MAUR_CLC-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/MAUR_CLC-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/MAUR_MIRA-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MAUR/MAUR_MIRA-CLC_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^
result_statistics/all_myco/MSCE_QUAST: 	$(MOLLI)/MSCe/MSCe_ABySS_35.fasta $(MOLLI)/MSCe/MSCe_CLC.fasta $(MOLLI)/MSCe/MSCe_MIRA.fasta \
result_assemblies/MSCe_AB_CLC_mix.fasta result_assemblies/MSCe_AB_MIRA_mix.fasta result_assemblies/MSCe_CLC_MIRA_mix.fasta datasets/GAA/Mycoplasmas/MSCe/MSCe_ABySS-CLC_gaa.fasta datasets/GAA/Mycoplasmas/MSCe/MSCe_ABySS-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MSCe/MSCe_CLC-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MSCe/MSCe_CLC-MIRA_gaa.fasta datasets/GAA/Mycoplasmas/MSCe/MSCe_MIRA-ABySS_gaa.fasta datasets/GAA/Mycoplasmas/MSCe/MSCe_MIRA-CLC_gaa.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/MSCe_ABySS-CLC_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/MSCe_ABySS-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/MSCe_CLC-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/MSCe_CLC-MIRA_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/MSCe_MIRA-ABySS_GAM.fasta datasets/GAM-NGS/Mycoplasmas/MSCe/MSCe_MIRA-CLC_GAM.fasta
	$(pyinterp) $(QUASTMOLLI) -o $@ $^


ALLMYCOQUASTS:result_statistics/all_myco/MSCD_QUAST result_statistics/all_myco/MSCc_QUAST result_statistics/all_myco/MSCb_QUAST result_statistics/all_myco/MOVI_QUAST result_statistics/all_myco/MMC_QUAST result_statistics/all_myco/MCCP_QUAST result_statistics/all_myco/MBVG_QUAST result_statistics/all_myco/MBOVb_QUAST result_statistics/all_myco/MAUR_QUAST result_statistics/all_myco/MSCE_QUAST